# Generated by Django 3.2.3 on 2022-05-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognititon', '0002_auto_20220528_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Criminal',
        ),
    ]
