# Generated by Django 3.2.3 on 2022-05-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerecognititon', '0003_rename_person_criminal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThiefLocation',
            new_name='CriminalLastSpotted',
        ),
    ]
